### ISSUE TITLE
Feature Advanced mode

### ISSUE THREAD

**Issue by maddypie** [maddypie/Pymanujan#11]
Currently, there is no option for advanced/extended mode for additional operations. PyCalc is limited to addition, subtraction, multiplication, division, and decimal operations only. The goal is to extend to more functionalities by **toggling** an *advanced* or *extended* button. The following features may be taken into consideration:
1. - [x] brackets-open/close `(` `)` 
     - From cec12766368e826250a69e65f68b9919e2c27700 brackets are entred using the keyboard in Basic mode.
     - Added in commit be65811f225928acbf918ac192d9b69add99d0bd.
2. - [x] power `^`
     - Added in commit 05515f9568ec4d4d74c001e5532a581e7b08f07a.
3. - [ ] factorial `!`
     - Logic to be added.
4. - [ ] logarithm `log`:  -> provide option for changing base 10
     - Logic to be added.
5. - [ ] trigonometric operations `sin` `cos` `tan`  -> provide option for changing radians to degrees
     - Logic to be added.

Discussion on implementation ideas is welcome :smile: .

**Comment by maddypie** [comment]
Fortunately, *Tkinter* supports `Notebook` widget. The base frame, `content` in changed to `ttk.Notebook` widget. After this change the UI now looks like this:

![PyCalc_basic_adv](https://user-images.githubusercontent.com/66778010/94586630-188ecf00-029f-11eb-80b5-024d29d56f3a.png)
> :green_circle:  : Basic mode
> :red_circle:  : Advanced mode

No new features are added to **Advanced** mode as of yet. All changes are being made in branch [mode_adv](https://github.com/maddypie/PyCalc/tree/mode_adv).

**Comment by maddypie** [comment]
New buttons were added for the advanced mode in PR #15.
**Note: Only button skeleton is added. Button logics are yet to be implemented.**
- :heavy_check_mark: **Button logic for `^` is implemented.**
![PyCalc-advanced](https://user-images.githubusercontent.com/66778010/94892763-1c8b3e80-04a3-11eb-92c7-5d158bd8e9e8.png)

**Comment by Olunusib** [comment]
Hi, I'm looking to add logic to the power and factorial buttons.

**Comment by maddypie** [comment]
@Olunusib, pleased to have you here. I want to point you that logic to power operator `^` was added in #16. 

>     Button logic for `^` is implemented.

Logic for **factorial** is yet to be implemented. You can take up take up the task of **adding logic** for the same. Let me know if you are ready to take up this task.

:smile: Cheers!

**Comment by Olunusib** [comment]
Yes, I’m ready.

**Comment by maddypie** [comment]
@Olunusib, I hope you are making progress? I would be glad to know the updates.
Cheers!! :smile:

**Comment by maddypie** [comment]
:sparkles: This issue is currently open. Write a comment if you are intrested in taking up this issue.

**Comment by nathdilla** [comment]
I can write the logic for factorial

**Comment by maddypie** [comment]
@nathdilla, many thanks for taking the time to contribute to this project. I apologise for late response. I am reviewing your PR.

**Comment by maddypie** [comment]
All the advanced button logic has been included as of d52a377397835d7e66945e3db20f00dcfad10932 (dev branch). Closing this issue for now. If any bugs are found this issue may be reopened.

P.S> This project has been renamed to `Pymanujan`. Please refer #23 announcement.
